### ISSUE TITLE
Extruder/toolhead parameters for HappyHare

### ISSUE THREAD

**Issue by pbutler** [SouthAsh1/Xol-metrix#9]
This is as much a question as a suggestion but I can't add labels:  

I might have missed it but does anyone have any dimensions/parameters for using this mod with Happy Hare.  I realize that these are dependent on the hotend/extruder choices but a wiki page where we could share parameters or other documentation could be helpful.  I know these can probably be measured in Fusion but I am not particularly adept at Fusion.

In particular the parameters below are what I am talking about.  There might be others but I took poor notes when I was setting this all up.  These shouldn't be held up as an example.  My tuning parameters are quite large and this was all hand tuned until I gave up and things mostly (but not always work):

In `mmu_parameters.cfg` (for a Rapido 2 SF and Orbiter 2).
```yaml
# Toolhead loading and unloading --------------------------------------------------------------------------------------
# ████████╗ ██████╗  ██████╗ ██╗     ██╗  ██╗███████╗ █████╗ ██████╗     ██╗      ██████╗  █████╗ ██████╗ 
# ╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██║  ██║██╔════╝██╔══██╗██╔══██╗    ██║     ██╔═══██╗██╔══██╗██╔══██╗
#    ██║   ██║   ██║██║   ██║██║     ███████║█████╗  ███████║██║  ██║    ██║     ██║   ██║███████║██║  ██║
#    ██║   ██║   ██║██║   ██║██║     ██╔══██║██╔══╝  ██╔══██║██║  ██║    ██║     ██║   ██║██╔══██║██║  ██║
#    ██║   ╚██████╔╝╚██████╔╝███████╗██║  ██║███████╗██║  ██║██████╔╝    ███████╗╚██████╔╝██║  ██║██████╔╝
#    ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝     ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚═════╝ 
#
# It is possible to define highly customized loading and unloading sequences, however, unless you have a specialized
# setup it is probably easier to opt for the built-in toolhead loading and unloading sequence which already offers a
# high degree of customization. If you need even more control then edit the _MMU_LOAD_SEQUENCE and _MMU_UNLOAD_SEQUENCE
# macros in mmu_sequence.cfg - but be careful!
#
# An MMU must have a known point at the end of the bowden from which it can precisely load the extruder. Generally this
# will either be the extruder extrance (which is controlled with settings above) or by homing to toolhead sensor. If
# you have toolhead sensor it is past the extruder gear and the driver needs to know the max distance (from end of
# bowden move) to attempt homing
#
toolhead_homing_max: 55			# Maximum distance to advance in order to attempt to home to defined homing endstop

# IMPORTANT: These next three settings are based on the physical dimensions of your toolhead
# Once a homing position is determined, Happy Hare needs to know the final move distance to the nozzle. There is only
# one correct value for your setup - use 'toolhead_ooze_reduction' (which corresponds to the residual filament left in
# your nozzle) to control excessive oozing on load. See doc for table of proposed values for common configurations.
#
# NOTE: If you have a toolhead sensor you can automate the calculation of these parameters! Read about the
# `MMU_CALIBRATE_TOOLHEAD` command (https://github.com/moggieuk/Happy-Hare/wiki/Blobing-and-Stringing)
#
toolhead_extruder_to_nozzle: 84		# Distance from extruder gears (entrance) to nozzle
toolhead_sensor_to_nozzle: 62		# Distance from toolhead sensor to nozzle (ignored if not fitted)
toolhead_entry_to_extruder: 8		# Distance from extruder "entry" sensor to extruder gears (ignored if not fitted)

# TUNING: The is a tuning setting that represents how much residual filament is left behind in the nozzle when filament
# is removed, it is thus used to reduce the extruder loading length and prevent excessive ooze.
# It is important to tune this parameter and not the dimensions above which are shared by other logic. If using a wipetower
# and you experience blobs on it, increase this value (reduce the quantity of filament loaded). If you experience gaps,
# decrease this value. If gaps and already at 0 then perhaps the 'toolhead_extruder_to_nozzle' setting is incorrect.
# Also see 'retract' setting in 'mmu_macro_vars.cfg' for final in-print blob tuning.
#
# NOTE: If you have a toolhead sensor you can automate the calculation of this parameter! Read about the
# `MMU_CALIBRATE_TOOLHEAD` command (https://github.com/moggieuk/Happy-Hare/wiki/Blobing-and-Stringing)
#
toolhead_ooze_reduction: 5		# Reduction in extruder loading length to fine tune ooze (default: 0mm)

# Distance added to the extruder unload movement to ensure filament is free of extruder. This adds some degree of tolerance
# to slightly incorrect configuration or extruder slippage. However don't use as an excuse for incorrect toolhead settings
#
toolhead_unload_safety_margin: 20	# Extra movement saftey margin (default: 10mm)
```

and in `mmu_macro_vars.cfg`:
```yaml
# Distance from the internal nozzle tip to the cutting blade. This dimension
# is based on your toolhead and should not be used for tuning
# Note: If you have a toolhead sensor this variable can be automatically determined!
# Read https://github.com/moggieuk/Happy-Hare/wiki/Blobing-and-Stringing
variable_blade_pos              : 51		; TUNE ME: Distance in mm from internal nozzle tip

# Distance to retract prior to making the cut, measured from the internal nozzle
# tip. This reduces wasted filament (left behind in extruder) but might cause a
# clog if set too large. This must be less than 'blade_pos'
# Note: the residual filament left in nozzle ('toolhead_ooze_reduction') is
# subtracted from this value so make sure toolhead is calibrated
variable_retract_length         : 35		; TUNE ME: 5mm less than 'blade_pos' is a good starting point
```
